frontend/reports/JunitXML, frontend/src/components/UserFeedPage/LoggedHomePage.test.js
This is a test for the LoggedHomePage component in user feed page, it has 100% coverage
=> Logged home test

frontend/src/components/Network/CreateEvent.test.js, frontend/src/components/Network/Event.test.js, frontend/src/components/Network/GroupNetwork.test.js, frontend/src/components/Network/PendingRequest.test.js, frontend/src/components/ProfileInfo/OtherUsersProfile.test.js, frontend/src/components/ProfileInfo/ProfileForm.test.js, frontend/src/components/UserFeedPage/LoggedHomePage.test.js, frontend/src/components/connection/ConnectionPage.test.js, frontend/src/components/connection/RequestSent.test.js, frontend/src/components/connection/RequestsPage.test.js, frontend/src/components/connection/Search.test.js
This pr includes 11 unit tests for respectively 11 pages components of the application to test the functionality of these pages. The results of these tests can be seen in the sprint 3 testing document.
=> Unit tests

frontend/package-lock.json, frontend/package.json, frontend/src/components/Network/CreateGroup.js
fix for dependency bug that prevented users from starting the application
deletion of react-image-editor-picker module which was causing the problems
=> fix for dependency bug

frontend/src/App.js, frontend/src/components/ProfileInfo/OtherUsersProfile.js, frontend/src/styles/network.css
- The user can have a cleaner view of the other user's profile after searching for their names
- The protection tag was added to all the routes
TODO
=> Fixed the styling of the other users profile

frontend/src/components/Network/GroupNetwork.js
=> P1 bug Revert "Minor Styling changes to Groups page"

frontend/src/App.js
- [done] added protected around JobPostings in App.js
=> Fixed the refresh bug pt2

frontend/src/components/authentication/SignIn.js
here we are removing the component for the time with the comment incase we need it in the future. however now it creates less confusion since there was no functionality for it.
=> fixing sign in page bug

frontend/src/components/Jobs/CreateNewPosting.js, frontend/src/components/Jobs/JobPostings.js
- [done[ Commented and Cleaned up the code for job postings and create job postings
=> Commented and Clean up on Job Postings

frontend/src/App.js, frontend/src/components/UserFeedPage/CreatPost.js, frontend/src/components/UserFeedPage/Feed.js, frontend/src/components/UserFeedPage/Post.js, frontend/src/styles/createpost.css
-Made creatPost capable of mutating state through useEffect 
-Made FeedDisplayment on Feed.js through fixing the markup for image uploading and data fetching 
-Added css to combine <input> and <img> for image uploading in creatPost.css
-Added wrappers around Feed and PostCreation routes to authorize access
=> Poste creation and feed display

frontend/src/components/Network/GroupNetwork.js
Ran into some issues with merges with main, but it's all fixed now.
Same description as #177.
=> Minor Styling changes to Group Cards #2

frontend/src/components/Navbar.js, frontend/src/components/connection/Search.js, frontend/src/styles/nav.css
=> Revert "adding navbar changes to my branch"

frontend/src/components/ProfileInfo/EditProfile.js, frontend/src/components/ProfileInfo/Profile.js, frontend/src/styles/profile.css
Changed the CSS and fixed some inconsistencies with the data formatting.
=> changed css

frontend/src/App.js, frontend/src/components/Jobs/ApplyNow.js, frontend/src/components/Jobs/ApplyToJobs.js, frontend/src/components/Jobs/CreateNewPosting.js, frontend/src/components/Jobs/JobPageForSeekers.js
- creation of ApplyToJobs page
- Changed name to ApplyNow
- formatted code of CreateNewPosting and reuse of its return for frontend
- Implementation the frontend of applynow page where phone number and additional files can be selected
- removed unused import
- Creation of JobPageForSeekers file and its page
- routing for JobPageForSeekers on App.js
=> 201 apply for jobs

frontend/src/components/Navbar.js
- Home icon button now directs user to Feed Page
=> Home icon button

frontend/src/App.js, frontend/src/components/Jobs/Advertisements.js, frontend/src/components/Jobs/CreateAdvertisement.js, frontend/src/components/Jobs/JobPostings.js
- Creation of advertisement.js file
- Implementing placeholder content in Advertisement page
- Routing of advertisement page on App.js
- Cloned JobPosting Page into ad page to base coding around its structure
- Creationg of CreateAdvertisement.js file
- CreateAd placeholder content implementation
- Routing for CreateAd added on App.js
- changed routing of sidebar in job pages
- changed colour of these clickable texts
- Sidebar changes on the ad side, clickable text colour and routing
- implementation of creation of advertisement and their storage on the database
- sidebar changes change of colour and text size
- Display of advertisements, the advertisements created by the user logged in will be shown in "Advertisement" tab accessible form the sidebar
- Added header for Advertisement & …
=> 39 posting advertisement as recruiter (Recruiter side)

frontend/src/components/connection/RequestsPage.js, frontend/src/styles/network.css
- User gets a confirmation of the successful connection after clicking on accept connection.
=> Add a pop up to confirm the connection was added

frontend/src/components/DirectMessage/Messaging.js, frontend/src/styles/Messaging.css
-Added a specific className so that it does not affect other files
-Moved the messaging css to the css folder
=> Modify general className

frontend/src/components/DirectMessage/Messaging.js, frontend/src/styles/Messaging.css
- Added focus to the user selected in the chat list to make it visually noticeable.
=> Add focus to chat list

frontend/src/styles/createpost.css
=> fix create post styling

frontend/src/components/Jobs/Advertisements.js, frontend/src/components/Jobs/ApplyNow.js, frontend/src/components/Jobs/CreateNewPosting.js, frontend/src/components/Jobs/JobPostings.js
- fixing ad text placement
- Added Advertise button in creation of job posting
- Changed style of the checkboxes
- Styling of skills bubbles on job postings to have them more distant to each other
- Advertise text indicator: job posting on recruiter end will let the recruiter know if that job posting is currently being advertised or not
- Ad page only shows job postings the recruiter chose to advertise
- removed create ad button, not needed by logic
- changed color of button in create job posting when clicked on
TODO
=> 39 posting advertisement as recruiter

frontend/src/components/ProfileInfo/EditProfile.js, frontend/src/components/ProfileInfo/ProfileForm.js
Bug related to images and resume and cover letters being stored as URLs is now solved. All entities are now stored in their respective user collections
=> 217 profile page images are not being stored as urls

frontend/src/components/UserFeedPage/Feed.js
bug related to fetching user full name on the feed has been fixed
=> fixed the bug related to fetching poster full name

frontend/src/components/UserFeedPage/Post.js, frontend/src/styles/post.css
- Added state variables and event handlers to manage likes, comments, and the display of the comment box.
- Implemented the handleLike function to update the number of likes when the like button is clicked.
- Created the handleCommentButtonClick function to show or hide the comment box when the comment button is clicked.
- Added the handleCommentSubmit function to handle the submission of comments, update the state with the new comment.
- Updated the styling for the post buttons to be responsive and maintain consistent proportions on smaller screens.
=> 17 liking and commenting posts

frontend/src/components/UserFeedPage/CreatPost.js
Add useNavigate to redirect to feed page after creating a post
=> post creation redirection fixed

frontend/src/components/authentication/JoinNow.js, frontend/src/components/authentication/SignIn.js, frontend/src/components/connection/ConnectionPage.js, frontend/src/components/connection/RequestSent.js, frontend/src/components/connection/RequestsPage.js
adding docstrings to files that had less documentation to it as well as adding small additional notes to them
=> Docstring additions

frontend/src/components/Jobs/JobPageForSeekers.js
- Added third party support, if a link has been put in the job posting by the recruiter, the "Apply Now" button on the job seeker's page will redirect them to the third party page
=> Added third party support

frontend/src/components/authentication/JoinNow.js
the information is now stored correctly based on which button someone selects:
they will be redirected to recruiter form or job seeker form based on their selection
=> fixing minor bug in signup

frontend/src/components/Jobs/ApplyNow.js
added contraints which disallowed duplicating the application and made that the applications are stored in an array owned by the recruiter
=> disallowing duplicating the application and applications are now stores in array

frontend/package-lock.json, frontend/package.json, frontend/src/App.js, frontend/src/components/Jobs/JobPageForSeekers.js, frontend/src/components/Jobs/SavedJobs.js, frontend/src/styles/JobPostings.css
- Implemented save posts button
- user can save job posts and unsave them 
- Added Saved Post page to display all the saved jobs
=> Save job posts

frontend/src/App.js, frontend/src/components/connection/CompanySearch.js, frontend/src/components/connection/Search.js, frontend/src/styles/CompanySearch.css
-Fixed bug where connect button changes to request for all users.
- Changed styling for search results.
- Changed styling for a list of users in a card with bio and work experience. 
- Added the connect button.
- Fixed some styling bugs, where the connect button was below the page.
- Fixed the styling bug for the profile image on the right instead of the left.
- Users can now successfully connect with other users using the search functionality.
=> 21 searching companies

frontend/src/components/Jobs/ApplyNow.js
- user cannot apply twice on the same job post
- user can apply to multiple different job post
=> Fixed job application bug

frontend/src/components/UserFeedPage/CreatPost.js, frontend/src/components/UserFeedPage/Feed.js, frontend/src/components/UserFeedPage/Post.js, frontend/src/styles/createpost.css, frontend/src/styles/feed.css, frontend/src/styles/post.css
the broken image icon will no longer be displayed when user only posts a text
=> Post creation and feed display

frontend/src/components/Jobs/JobPageForSeekers.js
- Applying to a third party posting will trigger a pop up before redirecting the user to the third party page
- added docstring for the handleRedirection method
- Comment explaining the purpose of JobPageForSeekers.js
- Added docstring for handleSave and handleUnsave methods
=> Apply pop up

frontend/src/components/UserFeedPage/CreatPost.js
- Fixed styling of Post button
- fixed navigation
=> [minor change] Fixed styling of Post button

frontend/src/components/UserFeedPage/Feed.js, frontend/src/styles/post.css
-changed color of green to correct one
-deleted carousel
=> changing elements in css for userfeed and userfeed page

frontend/src/components/ProfileInfo/OtherUsersProfile.js
=> adding a popup in otherusersprofile

frontend/src/components/Jobs/Advertisements.js, frontend/src/components/Jobs/JobPostings.js
- adding a pop up to confirm before delete: now users are asked to confirm they want to delete before they do so for error prevention and adding a user friendly aspect
- adding popup before deletes on advetrisements
now users are asked before they delete a advertisement so they don't do so accidentally
=> addings pop up for delete on job posting and advertisements

frontend/src/components/Jobs/CreateNewPosting.js
- Fixing document required checkbox bug in create job posting, the option to advertise, require resume and cover letter can now be unselected after selecting it
- Fixed Styling of the buttons to match the form
Fixing of bug #224
=> [bug fix] Fixing document required checkbox bug in create job posting

frontend/src/components/UserFeedPage/Post.js, frontend/src/styles/post.css
Removed the duplicate rendering of the username in the Post.js component, which was causing the username to appear three times on the feed page. Also, fixed the styling.
=>  Fix duplicate username display and style improvements

frontend/src/components/ProfileInfo/Profile.js, frontend/src/components/authentication/JoinNow.js
Users are now able to load in with a basic profile pic. closes issue #257
=> 257 users dont have profile pics when loaded

frontend/src/components/Jobs/CreateNewPosting.js, frontend/src/components/Network/CreateGroup.js, frontend/src/components/Network/GroupNetwork.js, frontend/src/components/Network/GroupPage.js, frontend/src/components/ProfileInfo/EditProfile.js, frontend/src/components/authentication/JoinNow.js, frontend/src/components/authentication/SignIn.js, frontend/src/components/connection/ConnectionPage.js
This PR adds modal pop-ups to provide a more informative and in-touch experience to users, as well as restrictions around certain text inputs so that empty documents do not crowd the database storage.
More specifically, this PR:
+ Allows users to see what went wrong when signing up (password < 6 char, existing user with same email)
+ Allows users to see what went wrong when signing in (wrong password, non-existing user)
+ Allows users to reconsider if they want to delete a connection, or leave a group.
+ Makes certain fields in the Group Creation and Job Posting Creation mandatory (title for example)
+ Restricts users to not be able to set their full name to an empty string.
Files/
[Modified] GroupPage.js
[Modified] GroupNetwork.js
[Modified] CreateNewPosting.js
[Modified] EditProfile.js …
=> Added restrictions/requirements/confirmations to text inputs and user decisions.

frontend/src/components/ProfileInfo/OtherUsersProfile.js, frontend/src/components/ProfileInfo/Profile.js, frontend/src/styles/network.css, frontend/src/styles/profile.css
Fixed the CSS for pages. Other users now display resume and cover letters.
=> 264 css and functionality of other users is not complete

frontend/src/components/Jobs/JobPageForSeekers.js, frontend/src/components/Jobs/SavedJobs.js, frontend/src/styles/JobPostings.css, frontend/src/styles/nav.css
- display the sponsored jobs at the top
- fix the search jobs bar
- display the apply button and saved button at the top of the job post
- fix the displayal of the saved jobs in the save job page
- fix the size of the picture in the search bar of the nav bar
=> Fix the job displayal for job seeker page 

frontend/src/components/UserFeedPage/Post.js, frontend/src/styles/post.css
made small changes to fix styling of feed page
=> Fix styling of feed page

frontend/src/components/DirectMessage/Messaging.js
- Fixed profile pictures in Chat-list
- Fixed profile picture for recipient
=> Fix profile pic for dm

frontend/src/components/UserFeedPage/Feed.js
- Removed sponsored posts from the Feed. They have been previously moved to job page for seekers page
- Was removed previously but conflict brought it back, this fixes it
=> [minor change] Removed sponsored posts from the Feed

frontend/src/components/UserFeedPage/Post.js
the broken image icon will no longer be displayed when user only posts a text
=> Fix issue of the broken image icon appearing in feed page

frontend/src/components/connection/Search.js
- Fixed Bug of list rendering in the serac box. Now , once submitted the list only renders on the navigated page.
- Commented Code for CompanySeach.js and Search.js.
=> Fix search bug

frontend/src/components/UserFeedPage/CreatPost.js, frontend/src/components/UserFeedPage/Feed.js
- Removal of sponsored post on feed (sponsored posts have been moved to job posting for seekers page)
- redirecting user to the feed after creation of a post
- slightly formatting the code
=> Newsfeed fixes

frontend/src/App.js, frontend/src/components/Navbar.js, frontend/src/components/Settings/ProfileInfoSetting.js, frontend/src/components/Settings/Security.js
- Created the setting pages linked to the ellipses on the nav bar
- Added the security pages 
TODO
=> Added the Settings pages

frontend/src/components/DirectMessage/Messaging.js, frontend/src/components/Jobs/ApplyNow.js, frontend/src/components/Jobs/CreateNewPosting.js, frontend/src/components/Jobs/JobPageForSeekers.js, frontend/src/components/Jobs/SavedJobs.js, frontend/src/components/Network/CreateGroup.js, frontend/src/components/Network/Event.js, frontend/src/components/connection/RequestSent.js, frontend/src/components/connection/RequestsPage.js, frontend/src/styles/GroupCreation.css, frontend/src/styles/JobPostings.css, frontend/src/styles/Messaging.css, frontend/src/styles/createpost.css, frontend/src/styles/feed.css, frontend/src/styles/network.css
- The styling of the following pages have been improved to accomodate different devices such as an iphone and an ipad: job posting, feed, group, job seeker posts, network pages
=> improve responsiveness of the pages

frontend/src/App.js, frontend/src/components/Settings/Notificationsettings.js, frontend/src/components/Settings/ProfileInfoSetting.js
- Created a new NotificationSettings.js component with form elements for DM and newsfeed notifications.
- Modified the ProfileInfoSettings.js file to navigate to the new `NotificationSettings` page when the user clicks on the "Notifications" link in the settings menu.
- Updated the routes in `App.js`  to include the `NotificationSettings` page.
=> Add notification settings for DMs and newsfeed

frontend/public/index.html, frontend/src/App.js, frontend/src/components/Jobs/JobPageForSeekers.js, frontend/src/components/Navbar.js, frontend/src/components/Notification.js, frontend/src/components/ProfileInfo/OtherUsersProfile.js, frontend/src/components/UserFeedPage/CreatPost.js
- The user receives notification when he receives an invite
- Added the route for notification page
- changed the title of app
- updated the post creation method to disallow empty posts from getting created
=> 20 notifications of events

frontend/src/App.js, frontend/src/components/Navbar.js, frontend/src/components/Settings/ChangePassword.js, frontend/src/components/Settings/Security.js, frontend/src/styles/nav.css, frontend/src/styles/setting.css
-User can change their password when logged in. 
- Modal components display error messages
-  Modified nav bar: Icon size are smaller
- Added a drop down for the setting and log out
=> add change password feature

frontend/src/components/Notification.js, frontend/src/styles/Notification.css
- notifications are shown in cards,
- added the notificatin center title
- added a notification.css file
=> Added styling to the notification page

frontend/src/App.js, frontend/src/components/Admin/Admin.js, frontend/src/components/Admin/AdminFeed.js, frontend/src/components/Admin/AdminUsers.js
- Create routing for admin page on app.js
- Creating admin page
- Added components of the admin page
- Made it so the recruiter that created the listing is shown
- Changed Sidebar tab from "advertisement" to "Feed Post"
- Created file where admin will be able to delete feed posts
- Added routing for adminfeed
- Modified routing for admin
- Building admin page
- Linking sidebar to adminfeed
- Deleted  unused .js
- Added delete function for admin that will allow them to delete any post in the system
- Delete button now deletes the map in which the text string belongs in
- Fixed network issue
- Display of post.id of each text
- Creation of admin user page to manage the users
- Making function to display all users
- Routing for user page for admin
- users can be deleted with the button
- …
=> 37 page management Added admin management for users, feed posts, and job posts

frontend/src/components/Navbar.js
=> fix redirect on navbar

frontend/src/components/Navbar.js
- Added an onClick and a constant to keep track of when to expand or not the navbar.
=> Navbar to collapse when clicked on

frontend/src/components/UserFeedPage/Post.js, frontend/src/styles/post.css
Added CSS to style the edit and delete buttons and changed their placement within the post container.
=> Update styling and placement of edit and delete post buttons

frontend/src/components/Admin/Admin.js, frontend/src/components/Admin/AdminFeed.js, frontend/src/components/Admin/AdminUsers.js, frontend/src/components/Jobs/JobPageForSeekers.js, frontend/src/components/UserFeedPage/CreatPost.js, frontend/src/styles/JobPostings.css
- Sponsored post styling fix
- The border of the card was made thinner
- The background colour was made to be matching the bacgrkound colour of the webapp page so the arrows of the carousel would be more apparent
- [minor fix] Job posting title on sponsored post fix, now showing
- Fixing admin user names showing
- Email of poster now showing on admin page for feed posts
- Slight styling adjustment
- Navigation bar working for feed post admin management
- fix colours
- Fixing side bar with routing on admin management pages
=> 37 page management 2

frontend/src/components/Settings/Notificationsettings.js, frontend/src/components/Settings/Security.js
- changed the color of clicked page
- added the navigation to other page from menu in Settings
=> Fixed the styling and connection between pages

frontend/src/App.js, frontend/src/components/Settings/NameSetting.js, frontend/src/components/Settings/Notificationsettings.js, frontend/src/components/Settings/ProfileInfoSetting.js, frontend/src/components/Settings/Security.js, frontend/src/styles/setting.css
- Add name and location page 
- Implemented the feature to modify first name, last name, city, and number in the settings
- Added modal for confirmation of changes
- [Fixed sidebar color styling]
=> Add change profile info in settings

frontend/src/components/Jobs/ApplyNow.js
- display a pop up when there is an error 
- display a pop up when use successfully sent an application
=> Add modal to job application

frontend/src/components/UserFeedPage/CreatPost.js, frontend/src/components/UserFeedPage/Post.js, frontend/src/styles/createpost.css, frontend/src/styles/post.css
1. fixed the issue with broken images being displayed in the Create Post component when the selected image is not loaded properly. It adds event handlers for image loading and error events and updates the image's display property accordingly.
2. Fixed styling of edit and delete buttons.
3. [Fixed position of the buttons for delete and update]
4. [Fixed styling of the user feed post buttons]
=> Hide broken image icon in Create Post component and fixed styling of edit and delete buttons

frontend/src/components/Jobs/Advertisements.js, frontend/src/components/Jobs/CreateNewPosting.js, frontend/src/components/Jobs/JobPageForSeekers.js, frontend/src/components/Jobs/JobPostings.js
- deadline of job posting during creation is sent to the database
- deadline shown on job postings on the recruiter page
- Deadline is now editable
- Made advertise button more specific
- Styled Job posting page for recruiter side
- Added delete advertisment button to remove it from being advertised
- Fixed styling and removed headers on top of the page
- Minor styling change to sidebar, removal of header in advertising
- Jobpagefor search bar can also look for companies now
- Apply Now button is disabled when the deadline has been past
- Job page for seekers page has been styled
=> Date expiration job postings

frontend/src/components/Jobs/Advertisements.js, frontend/src/components/Jobs/CreateNewPosting.js, frontend/src/components/Jobs/JobPageForSeekers.js, frontend/src/components/Jobs/JobPostings.js
=> Revert "Date expiration job postings"

frontend/src/components/Jobs/Advertisements.js, frontend/src/components/Jobs/CreateNewPosting.js, frontend/src/components/Jobs/JobPageForSeekers.js, frontend/src/components/Jobs/JobPostings.js
=> Revert "Revert "Date expiration job postings""

frontend/src/components/Jobs/Advertisements.js, frontend/src/components/Jobs/CreateNewPosting.js, frontend/src/components/Jobs/JobPageForSeekers.js, frontend/src/components/Jobs/JobPostings.js
=> Revert "Revert "Revert "Date expiration job postings"""

frontend/src/components/Navbar.js
=> Revert "Navbar routing"

frontend/src/components/Navbar.js
=> Revert "Revert "Navbar routing""

frontend/src/components/Jobs/Advertisements.js, frontend/src/components/Jobs/CreateNewPosting.js, frontend/src/components/Jobs/JobPageForSeekers.js, frontend/src/components/Jobs/JobPostings.js
=> Revert "Revert "Revert "Revert "Date expiration job postings""""

frontend/src/components/Jobs/JobPageForSeekers.js
Fixed formatting of date to show day of week, day, month and year
=> Fixed formatting of date to show day of week, day, month and year

frontend/src/App.js, frontend/src/components/Settings/Language.js, frontend/src/components/Settings/ProfileInfoSetting.js
deleted unneeded language component from the main
=> deleting language.js

frontend/src/components/Jobs/JobPageForSeekers.js, frontend/src/styles/JobPostings.css
- make all the skill button fit on the same card
- changed the height of the card to be adjustable
- Job seeker can apply on their phone
=> Job seeker page responsive on mobile

frontend/src/components/UserFeedPage/Post.js, frontend/src/styles/post.css
-changed size of edit and remove button
-remove unnecessary buttons on feed page
=> fix size of edit and delete buttons

frontend/src/components/Settings/ChangePassword.js, frontend/src/components/Settings/NameSetting.js
- recruiter are able to modify their general information
=> Fix bug name setting

frontend/src/components/Settings/ChangePassword.js, frontend/src/components/Settings/NameSetting.js
=> Revert "Fix bug name setting"

frontend/src/components/Settings/NameSetting.js
- Recruiter can add a contact number
=> Add the contact field for recruiter

frontend/src/components/UserFeedPage/CreatPost.js, frontend/src/components/UserFeedPage/Feed.js
- The default pictures show for user with not profile picture in feed
=> Add default picture to feed

frontend/src/components/Settings/Notificationsettings.js
- commented out the job notif option in settings
=> Comment out job notif

frontend/src/components/Notification.js, frontend/src/components/UserFeedPage/Post.js
- add default picture to comment
- add default picture to notification
=> add default picture

frontend/src/components/Jobs/CreateNewPosting.js, frontend/src/components/Jobs/JobPageForSeekers.js, frontend/src/components/Settings/Notificationsettings.js
add logic to notifications page for jobs, added a check on the jobseeker page to check whether the search bar is empty or not. fixed the collection name
=> fixed notifs showing
